// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	city "capstone-alta1/features/city"

	mock "github.com/stretchr/testify/mock"
)

// CityRepository is an autogenerated mock type for the RepositoryInterface type
type CityRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *CityRepository) GetAll() ([]city.Core, error) {
	ret := _m.Called()

	var r0 []city.Core
	if rf, ok := ret.Get(0).(func() []city.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]city.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCityRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCityRepository creates a new instance of CityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCityRepository(t mockConstructorTestingTNewCityRepository) *CityRepository {
	mock := &CityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
